### ISSUE TITLE
Know the unknown

### ISSUE THREAD

**Issue by BroderPeters** [jmattheis/UnknownProject#1]
Dieser Issue dient der Themensammlung, sowie dem allgemeinen Brainstorming.
1. Was soll entwickelt werden?
2. Mit welcher Programmiersprache soll es entwickelt werden? [Link](https://www.spieleprogrammierer.de/wiki/Spiele_programmieren_lernen)
3. Wie gewichtet sich die Aufgabenverteilung beziehungsweise wer übernimmt welche Rollen?
4. Was ist das Ziel? (Vermarktung, Endprodukt, Öffentlichkeit)
5. Unter welcher Lizenz tritt das Spiel in der Öffentlichkeit auf?
6. Haben wir eine Zielgruppe und wie gestaltet sie sich?

Edit: Fehler mit der Verlinkung wurde behoben.

**Comment by jmattheis** [comment]
1. (evtl coming soon)
2. Ich bin für C++ (mit DirectX um grafisch dinge darzustellen)
3. Würde das backend programmieren machen und mich auch einwenig in DirectX einarbeiten. 
4. Ein laufendes Spiel für Windows, was spaß macht lul (:

**Comment by BroderPeters** [comment]
1. Coming soon
2. Ich schließe mich Jannis Meinung an und stimme für C++, da es für seine Leistungsfähigkeit bekannt und weit verbreitet ist, was es uns erleichert im Internet nach Lösungen zu suchen.
3. Wie bereits angesprochen, wäre ich für die Grafische Gestaltung zuständig. Ich hoffe aber dass sich die Arbeiten nicht zu sehr auf die gewählten Bereiche beschränken, da jeder vermutlich aus jedem Bereich etwas lernen möchte.
4. Schließe ich mich ebenfalls Jannis an.

**Comment by nicolasries** [comment]
2. C++ ist in Ordnung. Was die Grafikschnittstelle angeht, finde ich OpenGL wegen der Plattformunabhängigkeit besser. Oder wir benutzen einfachere Bibliotheken wie [SFML](http://www.sfml-dev.org/) oder [SDL](https://www.libsdl.org/).
5. GPL klingt logisch.

Spielideen:
* RTS, ähnlich wie Age of Empires. Man kann Resourcen sammen, Einheiten und Gebäude bauen, den Gegner angreifen. 
* 2D FPS wie Doom
* RPG/Adventure im Stil von alten SNES Spielen. Echtzeit- oder rundenbasiertes Kämpfen.

Wir sollten das auf jeden Fall eher simpel halten und nicht zu ambitioniert werden. Deswegen wuerde ich auch erstmal bei 2D bleiben wollen.

**Comment by BroderPeters** [comment]
2D Ist auf jeden Fall ein Muss. Wir können alleine von den grafischen Gestaltungen her nicht hörer als pixelig gehen ^^.

**Comment by BroderPeters** [comment]
Stimme ebenfalls für die GNU PGL Lizenz.

Nebenbei, kann man Umfragen in Github erstellen?

**Comment by jmattheis** [comment]
ne kannst aber ne Umfrage auf [http://strawpoll.me/](http://strawpoll.me/) machen.

**Comment by BroderPeters** [comment]
Nach kurzem Gespräch mit @jmattheis haben wir uns entschloßen dass sich C++ doch nicht eignet, da es einiges an Erfahrung benötigt und fehleranfällig ist.

**Comment by BroderPeters** [comment]
http://strawpoll.me/7118409

**Comment by jmattheis** [comment]
I vote 4:
RPG/Adventure im Stil von alten SNES Spielen. Echzeit, mit verschiedenen Klassen Skillbäumen, Upgraden durch resourcen farmen

**Comment by BroderPeters** [comment]
I vote 4:
RTS, ähnlich wie Age of Empires. Man kann Resourcen sammen, Einheiten und Gebäude bauen, den Gegner angreifen.

**Comment by BroderPeters** [comment]
In Zusammenhang mit C# und den grafischen Schnittstellen:
[C# libraries for game development](http://gamedev.stackexchange.com/questions/109/what-c-libraries-can-be-used-to-support-game-development)
Die von @nicolasries vorgeschlagenen Schnittstellen sehen SFML, SDL, OpenGL auf den ersten Blick leicht und verständlich aus.
Um jedoch eine Entscheidung zu treffen welche Schnittstelle wir nutzen, sollte erst einmal klar sein, welche Art vor Spiel wir entwickeln um die Spezifikationen in den Schnittstellen zu suchen.

**Comment by jmattheis** [comment]
I vote 4 SDL (: hatte mir dazu schonmal ein tutorial angeschaut, das sah relativ gut aus, damit sind heutzutage auch noch 2d spiele gemacht die zb auf Steam sind.

**Comment by jmattheis** [comment]
Wir müssten uns hier mal entscheiden. das wir da weiter planen können.

---------
ich habe mir einwenig SDL2# angeschaut, und darüber gelesen das dort nicht all die funktionen vorhanden sind die in c++ da sind, dort müsste man dann ggf mal schauen was dort alles fehlt und wie wichtig das für uns ist.

**Comment by BroderPeters** [comment]
Programmiersprache dachte ich machen wir nun C#?
Hast du bereits bei AntWars deine geplannten DirectX oder OpenGL Tests durchgeführt, dass du ein Feedback auf dieses Projekt schließen kannst?

Name bringt nichts wenn wir kein grobes Konzept haben, da @nicolasries nicht nichts dazu gesagt hat, kommen wir diesbezüglich nicht weiter.

**Comment by nicolasries** [comment]
Sorry, hatte irgendwie übersehen, dass ihr hier schon weiterbesprochen habt..

Ich bin für RPG/Adventure, wobei man sagen muss, dass RTS wahrscheinlich um einiges einfach umzusetzen ist.
RPG erfordert mehr kreative Arbeit zuzüglich zur Programmierung wie Story, Setting, Grafiken, etc. Was es aber auch wieder interessanter macht.

Wenn wir mit C# arbeiten wollen und uns nur auf Windows fokusieren, bietet sich als Grafik/Sound-Bibliothek [Microsoft's XNA](https://msdn.microsoft.com/en-us/library/bb203894.aspx) an.
Dann ist noch noch die Frage, ob wir eine schon fertige Spiel-Engine wie Unity als Backend benutzen oder ganz unser eigenes Ding programmieren wollen. Ich bin da für letzteres.

**Comment by jmattheis** [comment]
Finde XNA in Ordnung damit ist ja auch das aktuelle Stardew Valley gemacht. 
Bzw Unity ist glaube DirectX somit können wir das nicht mit XNA benutzen, siehe [hier eine Liste von Game Engines](http://xboxforums.create.msdn.com/forums/t/12882.aspx).
Ich würde sagen wir schauen später ob wir eine GameEngine brauchen, wenn wir am Project arbeiten.

**Comment by BroderPeters** [comment]
RTS erfordet genauso Grafiken wie story bzw. inhaltliche Arbeit. Ich finde da eher ein RPG schwieriger, alleine schon wegen dem Hintergrund.

Aber ich habe nichts gegen ein RPG. Erstellen wir dieses dann mit einer "Draufsicht" ähnlich wie zb Diablo oder einer "Seitensicht" wie zb Terraria?

**Comment by jmattheis** [comment]
Ich wäre für eine Draufsicht.

**Comment by nicolasries** [comment]
Generell bin ich auch für Draufsicht. Kommt aber drauf an, wie unsere Spielidee aussieht.

**Comment by BroderPeters** [comment]
Oh gott.... wieso mache ich noch mal die grafiken!?

**Comment by jmattheis** [comment]
Ich habe mir xna gerade mal einwenig angeschaut, es scheint nicht sehr schwer zu sein, soein spiel zuentwerfen, Da denke ich das das aufwendigste die Grafiken sein werden, das da auch alles schön animiert ist.

**Comment by nicolasries** [comment]
Ja das sieht ganz praktikabel aus für unser Projekt finde ich.

**Comment by jmattheis** [comment]
Ich würde dann sagen, das wir eine Story ausarbeiten, mit der wir ja dann eigentlich alles haben was wir brauchen.

**Comment by BroderPeters** [comment]
Thema? Umgebung? Zeitalter? Fiktion oder Realität?

**Comment by BroderPeters** [comment]
Habe mir das noch einmal kurz durch den Kopf gehen lassen.
Muss es wirklich eine Draufsicht sein? So wie ich mir das aktuell vorstelle, müsste die Steuerung hierbei dreidimensional funktionieren. Hauptsächlich mache ich mir aber erhebliche Sorgen um die grafische Inszenierung. Es ist einfach viel schwieriger ein Objekt mit einer Draufsicht zu zeichnen, als eines aus der "Seiten-Sicht".

Wie seht ihr das Thema?

**Comment by nicolasries** [comment]
Ich dachte eher so an die alten SNES Spiele wie [Zelda](http://wiimedia.ign.com/wii/image/article/782/782613/virtual-console-au-buyers-guide-part-4-20070423084933753.jpg), wo man nach oben, unten, rechts und links laufen kann.

**Comment by BroderPeters** [comment]
Ok. So wäre super, Hatte etwas anderes im kopf.

**Comment by jmattheis** [comment]
Ich hatte auch an soetwas wie ein altes Zelda gedacht, ich denke nicht das das viel aufwendiger ist als eine Seiten Ansicht.

**Comment by BroderPeters** [comment]
Wie gesagt, ich habe mir da etwas falsches vorgestellt.

**Comment by BroderPeters** [comment]
> BroderPeters commented 7 days ago
>
> Thema? Umgebung? Zeitalter? Fiktion oder Realität?
@jmattheis @nicolasries Irgendwelche Vorschläge?

**Comment by nicolasries** [comment]
Generell fände ich Science-Fiction cool. Da hat man ziemlich viele kreative Möglichkeiten.
Ich glaube wir müssen aber erstmal noch das Spielprinzip genauer spezifizieren.

**Comment by jmattheis** [comment]
Hatte da an sowas ähnliches wie Diablo gedacht. Man tötet NPC's um Items zubekommen.
Zeitalter: es ist warscheinlich einfacher ältere Waffen wie Schwerter/Bögen zu pixeln (gibs bestimmt auch vieles Free to use). Umgebung: verschiedene würde ich mal sagen?.
Fiktion oder Realität?: Wäre für Fiktion, da man in einem RPG ja auch Fertigkeiten hat, dass diese auch außergewöhnlich sein können (:

**Comment by jmattheis** [comment]
Langsam wird das Issue ganz schön lang. Es wäre gut wenn der Inhalt von dem Issue mal auf einer Wiki Seite zusammengefasst wird. Möchte das einer von euch machen? sonst würde ich das übernehmen.

**Comment by BroderPeters** [comment]
Wenn du mir zeit lässt kann ich dass vielleicht am Sonntag machen, bin sonst ziemlich verplant am wochenende.

**Comment by BroderPeters** [comment]
[Nettes Beispiel der OpenTK-Möglichkeiten](https://dl.dropboxusercontent.com/u/10518681/Recordings/2G%202013-06-07%2018-32-47-35.webmvp8.webm)

**Comment by jmattheis** [comment]
Aber wir haben uns doch schon für XNA entschieden, es gibt bei XNA aber auch libraries die das machen [oder man macht es selbst](http://www.catalinzima.com/2010/07/my-technique-for-the-shader-based-dynamic-2d-shadows/)

**Comment by BroderPeters** [comment]
Ich habe dazu zwar nie meine Meinung geschrieben, aber ok.
Wieso benutzen wir dann bei AntWars wieder eine andere Grafik-API?

**Comment by jmattheis** [comment]
Zu der Zeit wo du das getestet hast stand das glaube noch nicht fest

**Comment by BroderPeters** [comment]
Dann finde ich sollten wir bei beiden Projekten die gleiche Grafik-API nehmen.
Und wenn wir uns wirklich auf Windows fixieren möchten, habe ich auch nichts gegen XNA.

**Comment by BroderPeters** [comment]
Was haltet ihr vom Spielkonzept à la "The Witcher 3"?

**Comment by jmattheis** [comment]
++, stimmt ja mit der Beschreibung die ich oben mal geschrieben hatte überein, dennoch brauchen wir hier immernoch ein Story.

**Comment by BroderPeters** [comment]
Jap Story...

Kam mir nur gerade so in den Sinn, da ich es mir heute mal gegönnt habe^^

**Comment by BroderPeters** [comment]
http://www.paladinstudios.com/2012/08/06/how-to-write-a-good-game-story-and-get-filthy-rich/

**Comment by jmattheis** [comment]
Wir machen ja keinen Worldeditor mehr, jetzt ist die frage ob wir eine eigene Gameengine bauen, welche dann letztendlich dazu da ist die map zuladen oder dort auch etwas schon fertiges nehmen?
ich wäre für eine eigene erstellen

**Comment by jmattheis** [comment]
Hätte ihr für die GameEngine eine Names-Idee?

**Comment by nicolasries** [comment]
Hab mir das Monogame kurz mal angeschaut. Das sieht gut aus und scheint ganz gängig zu sein, es gibt recht viele Dokus/Tutorials dazu.
Von mir aus können wir das benutzen.

**Comment by BroderPeters** [comment]
Stimme @nicolasries zu. Sieht handlich aus und hat n guten Ruf. Außerdem steht es für die Open-Source-Werte.

**Comment by nicolasries** [comment]
Ich mache das mal zu. Für Gameplay/Story ist ein neues Issue #14 aufgemacht, alles andere ist ja geklärt.
