### ISSUE TITLE
Abwesenheit

### ISSUE THREAD

**Issue by BroderPeters** [jmattheis/UnknownProject#11]
Da ich vom 08.05. bis zum 28.05.16 in Irland bin, kann ich nicht wirklich am Produkt mitarbeiten. Sobald ich wieder in Deutschland bin oder Zeit und die Kapazitäten in Irland habe, werde ich mir mal alles hier anschauen.

**Comment by nicolasries** [comment]
Alles klar. Viel Vergnügen in Irland :)

**Comment by BroderPeters** [comment]
@nicolasries @jmattheis Ich muss ja schon sagen, dass Thema wird durch die Issues, die hier die letzten Wochen erstellet worden sind, immer interessanter. (Auch wenn ich nur 35% gefühlt verstehe ^^)

**Comment by jmattheis** [comment]
@BroderPeters (:, wenn was nicht klar ist immer nachfragen, dadurch hat man dann gleich ein bisschen mehr dokumentiert :P

**Comment by BroderPeters** [comment]
@jmattheis Beziehe ich eher auf die Fachbegriffe oder Bereiche der Programmierung/Spieleentwicklung die ich noch gar nicht kenne.
