### ISSUE TITLE
Component Zeugs in ein eigenes Projekt verschieben.

### ISSUE THREAD

**Issue by jmattheis** [jmattheis/UnknownProject#17]

**Comment by jmattheis** [comment]
Hmm, hab mir mal ein paar gedanken gemacht. zu der Projekt Struktur

- ``UnknownProject`` würde ich in UnknownProject.UI umbennen
- ``UnknownProject.Tests``
- ``UnknownProject.Engine`` für die engine
- ``UnknownProject.Engine.Tests``
- ``UnknownProject.Core`` Für dto's (Datatransfer objects) wie zb configs, später player inventory usw, sollten sowenig logic wie möglich enthalten
- ``UnknownProject.Core.Tests`` jenachdem ob wir logic in core haben die wir testen müssen (obwohl das dann eigentlich nach Business kommt)
- ``UnknownProject.Business`` für Logik im backend, wie zb logik fürs das Generieren von Items, bewegen von Items im Inventar.
- ``UnknownProject.Business.Tests``

@nicolasries einverstanden damit?

**Comment by nicolasries** [comment]
Ja sieht okay aus

**Comment by jmattheis** [comment]
Ich überarbeite das hier drüber mal nochmal, da ich darin einige schwachstellen sehe
1. Normal Components sind unter ``UnknownProject.Components`` das was man für die components braucht ist unter ``UnknownProject.Core.Components``
--> Lösungsvorschlag ``UnknownProject.Components`` als eigenes Project (oder auch nicht siehe 2) und die interfaces und das core zeugs nach ``UnknownProject.Components.Core`` <-- das kann eigenes proj sein oder auch nur Unterordner in ``UnknownProject.Components``
2. Wir brauchen fast in jedem Projekt die monogame dll's die sind ca 4.5mb groß wenn wir viele projecte haben wird das gedoppelt
--> Lösungsvorschlag Alles in ein Project und Tests als eigenes Projekt mit einer guten Ordner struktur
Später wenn es zuviel wird kann man es ja immernoch in ein eigenes Projekt machen,
