### ISSUE TITLE
Konzept für Quests erstellen

### ISSUE THREAD

**Issue by jmattheis** [jmattheis/UnknownProject#18]
in diesem Issue soll ein Konzept für Quests erstellt werden.
* wie und wo gespeichert?
* Fortschritt wie und wo gespeichert
* usw

**Comment by BroderPeters** [comment]
Wie ebend mit @jmattheis angesprochen, sollten Quest in einer Datenbank für eine schnelle Verarbeitung abgespeichert werden. Ich schlage hierfür SQLite vor, welche ich selber bereits einmal kurz genutzt habe. Ist einfach zu initialisieren und zu nutzen (wie ein standard c# SQL connection)
- [Über SQLite](https://www.sqlite.org/about.html)
- [Besonderheiten](https://www.sqlite.org/features.html)
- [Passend für diese Umgebungen](https://www.sqlite.org/whentouse.html)

Eine Quest sollte folgenden Aufbau haben:
- Ansprechpartner
- Titel
- Beschreibung
- To-Do-List
- Belohnung (Gold/Item/Achievement)
- Orte auf der Karte (zur Verfolgung der Quest)

**Comment by jmattheis** [comment]
Ich füge hier mal noch was hinzu:
* Status 
  * active ( Momentane Quest die man verfolgt
  * done
  * failed
  * not_available ( Wenn die quest nicht verfügbar ist, und erst freigeschaltet wird
  * available ( Die kann man dann in der UI auf active stellen
* Ich finde Ansprechpartner, Belohnung, Orte auf der Karte nicht richtig, das sollte dann mit in der To-Do Liste sein
  * Die To-Do liste must du auch noch Spezifizieren
  

Hier wäre auch ein UML Diagramm gut

**Comment by jmattheis** [comment]
Hier wäre auch ein entity relationship model gut

**Comment by jmattheis** [comment]
Ich denke das es einfacher wäre Quests in selbst erstellte Definitions Dateien (zb xml für die deserialisierung) und man sich aus dieser dann jeweils eine DB erstellen kann, oder diese weiterverwendet.

Desweiteren brauch die Quest noch Freischalt Bedingungen und Verlier Bedingungen.
Diese können beispielweise andere Quests sein, Level, Rasse, Spielzeit?!?

**Comment by jmattheis** [comment]
Ich korrigiere mich noch einmal, es sollte keine Database geben, aus Questdefinitions Dateien sollte mit dem Charakter des Spielers eine Savestate Datei erstellt werden, wo Questfortschritt Level usw gespeichert wird.

**Comment by jmattheis** [comment]
Konzept:
* ein Tool für die Erstellung von Quests
* endresultat vomTool ist dann eine XML/XAML Datei mit dem QuestListe
* die XML wird über die Content Pipeline dann in eine XNB Datei gemacht, das wir diese im Spiel mit dem ContentManager holen können

**Aufbau von einer Quest**
* ID
* Namen 
* Beschreibung
* Freischalt Bedingungen
  * Min
  * Quest ID(s)
  * Spielzeit
  * Rasse
  * Interagieren mit Gegenstand/NPC
    * Dialog --> #53
* Fehlschlag Bedingungen
  * NPC Tot (Könnte auch zu einer Task Fehlschlag Bedingung)
  * gebrauchtes Item verkauft
  * Irgendwelche events halt
* Tasks
  * Task
    * Hier gibt es verschiedene Typen(Weiter unten aufgelistet)
    * Name/Beschreibung

**Task**

* Typen
  * Gehe zu Punkt X,Y auf Map Z
    * Zur Uhrzeit X
    * Töte Mobs (Finde loot von denen)
    * Suche einen Gegenstand
    * Interagiere mit NPC/Gegenstand
       * gebe Gegenstand ab
       * bekomme gegenstand
       * ... 
  * Folge NPC x,y
     * Punkt wo der NPC hinläuft(können mehrere sein)
  * ...

Ich werde es vielleicht später genauer machen, aber eigentlich geht es nur darum, das es einfach erweiterbar ist und man somit gut Quests erstellen kann.

**Wie geht es nun weiter?**

Innerhalb vom Spiel haben wir nun eine Liste mit Quests. Diese müssen wir dann auswerten und die Freischalt-Bedingungen überprüfen das müssten wir teoretisch ziemlich oft machen.

- [ ]  TODO hier muss es noch genauer geplant werden

**Speichern?**

Diese sollen mit in unsere Selbst erstellte SaveState Datei --> #54
Dort Kann zum Beispiel die QuestID und der Fortschritt als "TaskIndex" von der Liste gespeichert werden. Sodass diese SaveState Datei nicht alle Quests enthält

**Comment by BroderPeters** [comment]
Stimmt erstmal zu, vielleicht fallen mir später noch Ergänzungen ein.

**Comment by BroderPeters** [comment]
@jmattheis 

>  jmattheis commented 9 days ago

> Hier wäre auch ein entity relationship model gut

**Comment by jmattheis** [comment]
@BroderPeters wie du vielleicht gemerkt hast, ist in meinem Konzept keine Datenbank und somit wird auch kein ER-Modell gebraucht :P

**Comment by BroderPeters** [comment]
Failed.

**Comment by jmattheis** [comment]
done in #59
