### ISSUE TITLE
Git Commit Nachrichten

### ISSUE THREAD

**Issue by jmattheis** [jmattheis/UnknownProject#2]
Ich würde die Regeln aus http://chris.beams.io/posts/git-commit/ nehmen aber das "Template" einwenig verändern;
```
[ISSUE] kurze Zusammenfassung von den Änderungen (nicht mehr als ~50 Zeichen)

Was deine Änderung bringt

Weitere Infos
```

BSP:
```
[#2] fix big red button
 
After pressing the big red button a notification is shown 
instead of throwing exception.
 
additional: SomeHelper has now fancy method doSomething()
```
Damit haben wir dann etwas einheitliches und wissen immer zu welchem Issue welcher commit gehört.

Was haltet ihr davon?

**Comment by BroderPeters** [comment]
Finde ich gut. Englisch?

**Comment by jmattheis** [comment]
Englisch?

**Comment by nicolasries** [comment]
Ja das ist okay.
Pull Requests sollten auch etwas ausführlicher gestaltet werden. Als Beschreibung sollte dort alles ausgeführt werden, was der Pull Request verändert oder hinzufügt bzw. wozu er dient.

Ich fände Deutsch in Ordnung. Da wir unsere Issues auch in Deutsch schreiben, wäre es dann einfacher die spezifischen Punkte des Issues zu referenzieren.

**Comment by jmattheis** [comment]
Dafür hätte ich noch ein Issue erstellt, aber dann schreib ich das gleich hier, Ich fände es besser wenn wir Dokumentation/ git commits auch auf english schreiben. Da wir es ja "Open Source" machen sollten das ja viele verstehen.

**Comment by nicolasries** [comment]
Mit Dokumentation meinst du Code Kommentare, oder?
Englisch ist mir auch recht. Dann sollte aber der Code auch 100% englisch sein.
Bei den Issues bleiben wir aber bei Deutsch?

**Comment by jmattheis** [comment]
Ja, ich denke es ist einfacher das auf Deutsch zu machen. Evtl ändern wir das später wenn wir uns genug mit den frameworks auskennen (:

**Comment by BroderPeters** [comment]
Stimme dem zu.

> Englisch?

Damit meinte ich ob wir die Commits auf Englisch schreiben, hat sich ja nun erledigt.

**Comment by jmattheis** [comment]
Gut damit ist es entschieden.
