### ISSUE TITLE
WorldEditor

### ISSUE THREAD

**Issue by jmattheis** [jmattheis/UnknownProject#3]
Wenn wir eine Große Spielwelt haben wollen, wäre es aufdauer zu Aufwändig die Positionen von den Texturen immer selbst zu setzten.
Deswegen sollten wir in Erwägung ziehen, dort entweder einen fertigen Welten Editor zu benutzen oder einen eigenen zu erstellen. 

Wie steht ihr dazu?

**Comment by nicolasries** [comment]
Hast du einen schon fertigen als Beispiel?
Einen eigenen Editor zu programmieren wäre ziemlich interessant, wenn auch viel Arbeit.

**Comment by jmattheis** [comment]
Bis jetzt habe ich noch keinen gefunden der alles kann was wir brauchen,

Wir brauchen
* Collisions Map/Ebene
* Spawn Map/Ebene --> wenn wir random Spawnen von genern in Bereichen haben wollen
* Mehrere Ebene mit Texturen Ids

Ich nehme jetzt mal als Beispiel-Output das vom Editor [Tiled](http://www.mapeditor.org/). Dort gibt es nur das Erstellen mit Texturen nichts mit Collision oder anderes
Links Editor || Rechts die csv datei (tabellen datei) letzendlich einfach mit , getrennt.
![ss 2016-04-01 at 05 54 44](https://cloud.githubusercontent.com/assets/14895212/14212403/fcb56c74-f832-11e5-9773-29acaebd1bb4.png)
Eingelesen wir bei diesem Editor eine Bild Datei mit allen Texturen

Ich wäre eigentlich dafür einen Generischen Welten Editor als separates Projekt zu machen.

**Comment by nicolasries** [comment]
> Ich wäre eigentlich dafür einen Generischen Welten Editor als separates Projekt zu machen.

Das war auch mein Gedanke. Wäre nochmal etwas anderes und bestimmt auch interessant als Programmierprojekt.
Damit könnten wir auch schon anfangen, ohne unser Spiel vollständig durchkonzipiert zu haben.

Ich bin dabei.

**Comment by jmattheis** [comment]
--> https://github.com/jmattheis/WorldEditor <--

**Comment by jmattheis** [comment]
Kleiner Edit: Tiled kann anscheinend doch alles was wir brauchen, ich halte es trotzdem für besser einen eigenen  zu erstellen, sei es auch nur wegen dem lern Effekt (:

**Comment by BroderPeters** [comment]
Jetzt verstehe ich worum es geht.
@jmattheis habe vorhin unterwegs nur die E-Mails von Github gesehen und mir NUR das Konzept vom Worldeditor angesehen, da hat ein wenig der Kontext gefehlt.

@jmattheis @nicolasries Bitte denkt daran, dass wir AntWars Präsentationsfähig abschließen müssen. Die Ideen sind zwar toll und umfangreich, ich würde jedoch bevor wir etwas neues anfangen, gern das Schulprojekt abhacken können.
