### ISSUE TITLE
Configfile format

### ISSUE THREAD

**Issue by jmattheis** [jmattheis/UnknownProject#33]
Ich würde für etwas einfaches wie zb eine .ini Datei oder eigentlich nur ein ``key=value`` welches man ja relativ einfach auslesen kann.
Gegenstimmen?

**Comment by jmattheis** [comment]
Hier würde es beispielsweise [SharpConfig](https://github.com/cemdervis/SharpConfig) geben.

**Comment by nicolasries** [comment]
Bin ich einverstanden. Von mir aus können wir auch gleich SharpConfig nehmen, das sieht ganz gut aus.

**Comment by BroderPeters** [comment]
Stimme auch zu
