### ISSUE TITLE
Teammeeting #1

### ISSUE THREAD

**Issue by jmattheis** [jmattheis/UnknownProject#38]
Wie in der Schule besprochen wollten wir ein Teammeeting machen um das weitere vorgehen zu besprechen.

Wann hättet ihr dazu Zeit?

**Comment by BroderPeters** [comment]
Ich kann am Samstag. Ansonsten nächste woche

**Comment by nicolasries** [comment]
Samstag ist in Ordnung

**Comment by jmattheis** [comment]
Samstag ist für mich auch OK, an welche Uhrzeit hättet ihr da so gedacht? @BroderPeters @nicolasries

**Comment by nicolasries** [comment]
Eher gegen Abend, so 19:00?

**Comment by BroderPeters** [comment]
Puh, lasst uns morgen darauf einigen

**Comment by jmattheis** [comment]
Samstag 17 Uhr abgemacht

**Comment by BroderPeters** [comment]
Ergebnisse Teammeeting:
* lootorientiertes Coop (Diablo-like)
 * Keine Coop-Rätsel
* Spracheinbindung = späteres Feature
 * gängige Soundeffekte und Musik integriert
* Issues angucken
* Konzepte verfassen
* Unklarheit --> Fragen!
* Jannis
 * Engine
* Nico
 * AI
 * Menü
 * GUI
* Broder
 * Hauptverantwortlicher Story-Writer
   * passives Feedback durch andere Mitarbeiter

**Comment by BroderPeters** [comment]
Kann der Issue geschlossen werden?

**Comment by jmattheis** [comment]
Ich denke schon, vielleicht sollten die Ergebnisse auf einer Wiki Seite festgehalten werden.

**Comment by BroderPeters** [comment]
@jmattheis na dann mach das mal (;

**Comment by jmattheis** [comment]
https://github.com/jmattheis/UnknownProject/wiki/Meeting-Results
