### ISSUE TITLE
Unit Test - Framework

### ISSUE THREAD

**Issue by jmattheis** [jmattheis/UnknownProject#4]
Da wir uns ja entschieden haben Test zu schreiben stellt sich hier die Frage welches Testing-Framework wir benutzen, im Grunde unterscheiden die sich nicht viel.
http://stackoverflow.com/questions/261139/nunit-vs-mbunit-vs-mstest-vs-xunit-net

Mir ist es eigentlich relativ egal welches wir benutzen, ich würde mich nur gegen MSTest entscheiden,  da dies nicht mit den [continuous integration](https://de.wikipedia.org/wiki/Kontinuierliche_Integration) - Systemen kompatible sind, diese sind zb dafür da in jedem Pullrequest alle Tests (wenn wir welche haben) automatisch auszuführen.
Von dem was ich gelesen haben würde ich mich entweder für NUnit oder XUnit entscheiden.
Was denkt ihr da?

**Comment by nicolasries** [comment]
Ich hab mal ein bisschen mit dem NUnit Plugin in Visual Studio rumprobiert. Das funktioniert ganz gut. Können wir nehmen von mir aus.
Doku unter https://github.com/nunit/docs/wiki

**Comment by nicolasries** [comment]
Hattest du schon ein continuous integration-System im Sinn? Ich kenne nur Travis ein bisschen.

**Comment by jmattheis** [comment]
jep travis ci

**Comment by jmattheis** [comment]
Ich würde dann auch einen MVC ansatz ansteuern, da es schwer ist soetwas zutesten, wie zb das ein text gezeichnet wird, da wir da ein initialisiertes game-object brauchen, welches monogame/xna mit static variablen irgentwo mit magic initialisert. 
Ich versuche dort mal ein konzept zuentwerfen.

**Comment by nicolasries** [comment]
Das kann zu, oder? Wir haben uns ja für NUnit+FakeItEasy und Travis CI entschieden.

**Comment by jmattheis** [comment]
Yep.
