### ISSUE TITLE
Spritebatch

### ISSUE THREAD

**Issue by jmattheis** [jmattheis/UnknownProject#5]
Ich weiß jetzt nicht wie weit ihr dort im Thema seid, ich frage einfach mal trotzdem.

Laut dem was ich gelesen habe zb [Stackoverflow Antwort](http://stackoverflow.com/a/13970974/4244993)
Soll man die Spritebatch nur einmal Initialiseren und dann wieder benutzen über zb eine Static variable

Ich halte von static variablen aber nicht viel, da man diese schlecht testen, deswegen würde ich vorschlagen das wir unser eigenes ``IDrawable`` interface implentieren welches inetwa so aussehen sollte

```
interface IDrawable {
    int DrawOrder { get; }
    bool Visible { get; }

    event EventHandler<EventArgs> DrawOrderChanged;
    event EventHandler<EventArgs> VisibleChanged;

    void Draw(SpriteBatch spriteBatch, GameTime gameTime); // <-- die spritebatch mit drin
}
```
Seid ihr damit einverstanden?, dadurch können wir das standart handling von xna nicht benutzen und mussen etwas eigenes machen.

**Comment by nicolasries** [comment]
Kann man die `SpriteBatch` Instanz nicht im jeweiligen Objekt dem Konstruktor übergeben und als Attribut speichern?

**Comment by jmattheis** [comment]
das wäre natürlich teoretisch möglich, praktisch aber können wir dann das component nicht mehr über dependency injection im constructor vom Game injecten, da es nicht möglich ist die spritebatch dort zu erstellen.
