### ISSUE TITLE
Label-Konventionen

### ISSUE THREAD

**Issue by BroderPeters** [jmattheis/UnknownProject#50]
Mir ist soeben aufgefallen, dass sich unter die bisher standardmäßig englischen Label eine deutsche Bezeichnung `grafiken` geschummelt hat. Ich finde wir sollten hierbei einheitlich bleiben.

Desweiteren noch meine Frage, könenn wir ein Label für die Story hinzufügen?

![2016-06-26 21_43_51](https://cloud.githubusercontent.com/assets/5406341/16364453/4e26b548-3be7-11e6-9da9-520913559701.png)

**Comment by jmattheis** [comment]
done
