### ISSUE TITLE
Konzept für Dialoge

### ISSUE THREAD

**Issue by jmattheis** [jmattheis/UnknownProject#53]
Es wird später viele Dialoge geben, deswegen sollten wir diese auch nicht Hardcodiert festlegen sondern in "Dialoge Definitions" Dateien bsp xml/YML.
Hier soll ein Konzept für diese erstellt werden.

**Comment by BroderPeters** [comment]
Oh gott bloß nicht hardcodiert!
Wollten wir nicht eventuell sogar mehrere Sprachen anbieten?

**Comment by jmattheis** [comment]
Yep, in der Dialog-Definitions Datei wird dann nur ein Text-Key gespeichert zu welchem es dann mehrere Sprachen gibt.

**Comment by BroderPeters** [comment]
Nice.

**Comment by jmattheis** [comment]
done in #68
