### ISSUE TITLE
Quest/Dialog getrennt?

### ISSUE THREAD

**Issue by jmattheis** [jmattheis/UnknownProject#67]
Soll die Quest von dem Dialog getrennt werden? Eigentlich finde ich das diese zusammen passen und dadurch in einer questdialog definitions datei sein sollten

Eure Meinung?
@BroderPeters @nicolasries @ColinWojciechowski

**Comment by BroderPeters** [comment]
Der Dialog einer Quest soll mit in der Quest gesichert werden.

**Comment by jmattheis** [comment]
siehe #68
