### ISSUE TITLE
WPF Konventionen

### ISSUE THREAD

**Issue by BroderPeters** [jmattheis/UnknownProject#70]
Für die Entwicklung des QDIN-Tools(#69) sollten für bspw. die Bezeichnung der Buttons oder Click-Events Konventionen festgelegt werden.

**Comment by jmattheis** [comment]
nimm die standard konventionen.

**Comment by BroderPeters** [comment]
Werde mich an den Konventionen aus [AntWars](https://github.com/jmattheis/AntWars/wiki/Konventionen), welche sich an [diesen](https://msdn.microsoft.com/en-us/library/aa263493%28v=vs.60%29.aspx/) orientieren. 

Für WPF scheint es bei erster Suche keine offizielen Guidelines zu geben.
