### ISSUE TITLE
Level Condition?!?

### ISSUE THREAD

**Issue by jmattheis** [jmattheis/UnknownProject#71]
StoryMaster( @BroderPeters ) ist die Level Condition wichtig, oder machen wir das so ähnlich wie in The Witcher das da ein empfohlenes level ist, aber man trotzdem die Quest für höhere level schon freischaltet?

**Comment by BroderPeters** [comment]
Ich finde das empfohlene Level reizvoller. So erhält der Spieler eine grobe Einschätzung der Schwierigkeit, kann aber auch sein Können versuchen und besseres Loot abstauben. Eine Einschränkung wird es hierbei bei Hauptquest geben, welche erst zum Zeitpunkt X oder nach Quest Y abgeschlossen werden können.

**Comment by jmattheis** [comment]
Zeitpunkt X ?

**Comment by BroderPeters** [comment]
Mit Zeitpunkt meinte ich ne bestimmte Bedingung, wie Item oder so ^^

**Comment by jmattheis** [comment]
Level wurde gelöscht.
