### ISSUE TITLE
Quest Dialog IDs ?!?

### ISSUE THREAD

**Issue by jmattheis** [jmattheis/UnknownProject#72]
@BroderPeters  du machst ja das QDIN tool, dort gibt es ja IDs eigentlich würde ich die im tool nicht anzeigen. Deswegen könnten das ja auch Int's sein, dann würde das performanter sein, da man die in ein Array packen könnte, wäre das k? Dann wäre das auch einfacher wenn das das Programm festlegt, da die ID als string ja von nutzter festgelegt werden müsste und da kann es ja zu duplicates kommen.

**Comment by BroderPeters** [comment]
Approved.
Find ick gut und logisch.
